version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend/db/data/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    container_name: farm-app-db-dev
  
  backend:
    image: farm-app-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=farm-app-db-dev
      - DB_PORT=${DB_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    container_name: farm-app-backend-dev
    depends_on:
      - db

  frontend:
    image: farm-app-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:${SERVER_PORT}/api
    container_name: farm-app-frontend-dev