version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend/db/data/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    container_name: farm-app-db-dev

  test-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${TEST_DB_PORT}:5432
    container_name: farm-app-test-db-dev 