name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up node
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Build frontend
          run: cd backend && npm run build && mv build ../frontend

        - name: Set up flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: Deploy app
          run: flyctl deploy