name: Fly Deploy
on:
  workflow_run:
    workflows: ["Backend tests"]
    branches: [main]
    types:
      - completed
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16.8.0'

      - name: Build frontend
        run: cd frontend && npm install && npm run build && rm -rf ../backend/build && mv build ../backend

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: cd backend && flyctl deploy